apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-user-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: controller-role
subjects:
- kind: ServiceAccount
  name: podperconn
#- apiGroup: rbac.authorization.k8s.io
#  kind: User
#  name: user
