apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller-role
rules:
- apiGroups:
  - ""
  - "apps"
  resources:
  - pods
  - deployments
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-user-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: controller-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user
# - apiGroup: rbac.authorization.k8s.io
# kind: ServiceAccount
# name: sauser
